### ISSUE TITLE
Party-Stammdaten - Eingangswizard

### ISSUE THREAD

**Issue by rennerl** [PartyGuruTeam/partyguru#11]
- Uhrzeit
- Datum
- Motto
- Ort

**Comment by bastianharren** [comment]
Bug beim laden der Stammdaten

**Comment by rennerl** [comment]
Funktionen Datum/Zeit integriert und getestet (Harren & Renner)

**Comment by rennerl** [comment]
Wizard in Form der Java-Applikation implementiert und getestet
