### ISSUE TITLE
Party-Stammdaten - Schlaf- /Mitfahrgelegenheit

### ISSUE THREAD

**Issue by rennerl** [PartyGuruTeam/partyguru#12]
Selbst zu pflegende Datenbank für Betten-/Mitfahrgelegenheiten.

**Comment by lorddurin** [comment]
Integriert

**Comment by rennerl** [comment]
Gelegenheiten können angelegt werden.
Modifikationen in der Darstellung nötig, Spaltennamen, etc.

**Comment by rennerl** [comment]
Gelegenheiten implementiert und getestet.
Zuweisung erfolgreich.
