### ISSUE TITLE
Kontaktmanagement - Mitbringliste

### ISSUE THREAD

**Issue by rennerl** [PartyGuruTeam/partyguru#14]
Verknüpfung vom Planer erstellt der Gästeliste und der Einkaufsliste.

**Comment by lorddurin** [comment]
Integriert

**Comment by rennerl** [comment]
BUG: 
NULL nicht zulässig für Feld "PERSID"
NULL not allowed for column "PERSID"; SQL statement:
INSERT INTO Material (MTID, PID) VALUES ('2','36') [23502-187]

**Comment by rennerl** [comment]
BUG behoben (vor 2 Wochen).
Mitbringliste kann generiert werden und Essen/Getränke und Utensilien können einer Person zugewiesen werden.
Testing erfolgreich.
