### ISSUE TITLE
Kontaktmanagement - Pärchengenerierung

### ISSUE THREAD

**Issue by rennerl** [PartyGuruTeam/partyguru#15]
Automatische  Zuordnung von Pärchen aus der Gästeliste (Stammdaten).

**Comment by Sapalotti** [comment]
- Stati hinzufügen bei Personen (Kontakte)

**Comment by Sapalotti** [comment]
Hoppla :-) Kleines Layer 8 Problem...

**Comment by rennerl** [comment]
Durch Franzi: Logik implementiert.
Grafische Funktion noch ausstehend.

**Comment by rennerl** [comment]
Durch Franzi: Bugs in Pärchengenierung behoben.
GUI implementiert und in Applikation integriert.

**Comment by rennerl** [comment]
Testing erfolgreich.
