### ISSUE TITLE
Materialmanagement

### ISSUE THREAD

**Issue by rennerl** [PartyGuruTeam/partyguru#19]
Vorausgefüllte Liste für Speisen, bei der die gewünschten Speisen angekreuzt werden sollen und dann als fertige Liste ausgegeben werden können.

Speisen / Getränke / Partyutensilien (als jeweilige Unterkategorien)

**Comment by lorddurin** [comment]
Template erzeugt

**Comment by rennerl** [comment]
Es können entsprechende Materialien angelegt und ausgewählt werden.

**Comment by rennerl** [comment]
Materialien können angelegt und ausgewählt werden.
Außerdem können diese der Mitbringliste hinzugefügt werden.
Testing erfolgreich.
