### ISSUE TITLE
UML Diagramm

### ISSUE THREAD

**Issue by bastianharren** [PartyGuruTeam/partyguru#4]

**Comment by rennerl** [comment]
Klassendiagramme (UML-Notation) unter Berücksichtigung der DB-Entwürfe erstellt:

Folgende Arbeiten sind bereits erledigt:
- Notwendige Klassen/Interfaces definiert.
- Membervariablen und jeweilige Datentypen definiert.

Noch vollständig abschließen:
- Notwendige Funktionen/Methoden für die jeweiligen Klassen definieren

**Comment by rennerl** [comment]
Außerdem noch notwendig:

Klassendiagramme (UML) für GUI und DB

**Comment by rennerl** [comment]
UML-Diagramm erstellt und hochgeladen.

Unterscheidung in Version 1 und 2.
UML-Diagramm 2 ist die weiterentwickelte Version.
