### ISSUE TITLE
GUI Grundgerüst

### ISSUE THREAD

**Issue by bastianharren** [PartyGuruTeam/partyguru#8]

**Comment by rennerl** [comment]
GUI-Reiter und GUI-Menü erstellt.
Derzeitige Erarbeitung: Teilung der GUI in unterschiedliche Bereiche.

**Comment by lorddurin** [comment]
Oberfläche mit Swing erstellt
Kategorien und Reiter programmiert

**Comment by bastianharren** [comment]
TabellenLayout erstellt und Anbindung an DB getestet

**Comment by rennerl** [comment]
Formularerstellung begonnen.

Optimierungen durchgeführt.
